name: Awesome CircuitPython sync

on:
  push:
    branches:
      - master
  schedule:
    # run every monday at 9am
    - cron: */10 * * * *

jobs:
  check-repo-owner:
    # This job is so the entire workflow will end successfully and give some
    # output to explain why it hasn't run on a non-Adafruit fork.
    runs-on: ubuntu-latest
    steps:
      - name: repository
        env:
          OWNER_IS_ADAFRUIT: ${{ startswith(github.repository, 'adafruit/') }}
        run: |
          echo "This workflow will only run if Adafruit is the repository owner."
          echo "Repository owner is Adafruit: $OWNER_IS_ADAFRUIT"

  build:
    runs-on: ubuntu-latest
    # Only run the build on Adafruit's repository. Forks won't have the secrets.
    # Its necessary to do this here, since 'schedule' events cannot (currently)
    # be limited (they run on all forks' default branches).
    # if: startswith(github.repository, 'adafruit/')
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name : Update, commit and push submodule updates
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git submodule update --init --remote -- awesome-circuitpython
        git add awesome-circuitpython || echo "No changes to add"
        git commit -m "Updated awesome-circuitpython submodule" || echo "No changes to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
