name: Jekyll site CI

on: 
  push:
    branches:
      - master
      - actions
      - libraries
  schedule:
    - cron: 0 10 * * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: "6f404dac52d9171618a4be20c6c75f708cc10cf6"
        submodules: true
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod 777 /srv/jekyll && jekyll build --future"
