name: Jekyll site CI

on:
  push:
    branches:
      - master
      - actions
      - libraries
  schedule:
    - cron: 0 10 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.x'
    - name: Build the site in the jekyll/builder container
      run: |
        bundle install
        bundle exec jekyll build -d build
        cd build
        touch .nojekyll
        # https://github.com/helaili/jekyll-action/blob/master/entrypoint.sh#L49
        git init
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add .
        git commit -m 'jekyll build from Action'
        git push --force https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git HEAD:gh-pages
        rm -fr .git
        cd ..
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
